name: Store API CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: store-api
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
         distribution: temurin
         java-version: 26

      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      - name: build and test
        run: ./mvnw clean package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: store-api
          path: store-api/target/*.jar

  docker:
    needs: build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: store-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: store-api
          path: store-api/target

      - name: Build Docker image
        run: docker build -t ghcr.io/alysaied/store-api:${{ github.sha }} .

      - name: Login to GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker push ghcr.io/alysaied/store-api:${{ github.sha }}

  deploy:
    needs: docker
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: production
    runs-on:
      - self-hosted
      - Linux
      - X64
    steps:
      - name: Pull new Docker image
        run:
          docker pull ghcr.io/alysaied/store-api:${{ github.sha }}
      - name: Save previous image
        run: |
          if docker inspect store-api-container >/dev/null 2>&1; then
            PREVIOUS_IMAGE=$(docker inspect store-api-container --format='{{.Config.Image}}')
            echo "PREVIOUS_IMAGE=$PREVIOUS_IMAGE" >> "$GITHUB_ENV"
            echo "Previous image: $PERVIOUS_IMAGE"
          else
            echo "PERVIOUS_IMAGE=" >> "$GITHUB_ENV"
            echo "No pervious container found"
          fi
      - name: Remove old container
        run: docker rm -f store-api-container || true
      - name: Start new container
        run: |
          docker run -d \
            --name store-api-container \
            --restart unless-stopped \
            -p 8080:8080 \
            -e APP_ENVIRONMENT="${{vars.APP_ENVIRONMENT}}" \
            ghcr.io/alysaied/store-api:${{ github.sha }}
      - name: Verify deployment
        run: |
          echo "waiting for Store API to become healthy..."
          
          for i in {1..10}; do
            if curl -f http://localhost:8080/api/this-endpoint-does-not-exist; then 
              echo "Store API is healthy"
              exit 1
            fi
            echo "Attempt $i failed. Retrying in 5 seconds..."
            sleep 5
          done 
          echo "Store API failed health check"
          docker logs store-api-container
          exit 1
      - name: Rollback deployment
        if: failure()
        run: |
          echo "New deployment failed."
          if [ -z "$PREVIOUS_IMAGE" ]; then
            echo "No previous image available for rollback."
            exit 1
          fi
          echo "Rolling back to: "$PREVIOUS_IMAGE"
          
          docker rm -f store-api-container || true
          
          docker run -d \
            --name store-api-container \
            --restart unless-stopped \
            -p 8080:8080 \
            "$PREVIOUS_IMAGE"
          echo "Rollback completed."