name: Store API CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: store-api
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
         distribution: temurin
         java-version: 26

      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      - name: build and test
        run: ./mvnw clean package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: store-api
          path: store-api/target/*.jar

      - name: Build Docker image
        run: docker build -t store-api:1.0 ./store-api
